In [6]:
import numpy as np
import torch

In [7]:
# numpy >> pytorch 변환
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)
# 행렬 변환 - 2차원 ♣
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)
# 행렬 변환 - 3차원 ♣
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [8]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
# 행렬 변환 - (해당 dim에 1인 차원 제거) ♣
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [9]:
ft = torch.FloatTensor([0, 1, 2])
print(ft)
print(ft.shape)
# 행렬 변환 - (해당 dim에 1인 차원 추가) ♣
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)
# 행렬 변환 - 2차원 ♣
print(ft.view(1, -1))
print(ft.view(1, -1).shape)
# 행렬 변환 - (해당 dim에 1인 차원 추가) ♣
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)
# 행렬 변환 - (해당 dim에 1인 차원 추가) ♣
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([0., 1., 2.])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [10]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
# 행렬 자료형 변환
print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt)
# 행렬 자료형 변환
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [11]:
x = torch.FloatTensor([[1, 2],[3, 4]])
y = torch.FloatTensor([[5, 6],[7, 8]])
# 행렬 연쇄
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [12]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
# 행렬 스택
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim = 1))
# 행렬 연쇄로 구현
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)) # ♣

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [13]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
# Ones, Zeros
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
