Pytorch 공부 사이트 : https://wikidocs.net/52460  

 1. 목차  
	1) Data definition(데이터 정의)  
	2) Hypothesis(모델 가정)  
	3) Compute loss(손실 측정)  
	4) Gradient Descent(경사 하강법)  
 2. Linear Regression : 1개의 데이터 다룸  
    1) Data definition(데이터 정의)  
<img src="./Data_definition.png" width="200" height="200">  
        (1) Traing dataset정의  
            입력 : x_train = torch.FloatTensor([인덱스 범위])  
            출력 : y_train = torch.FloatTensor([인덱스 범위])  
        (2) Test dataset정의  
            입력 : x_test =  
            출력 : y_test =  
    2) Hypothesis(모델 가정)  
<img src="./Hypothesis.png" width="300" height="300">  
        (1) # Hypothesis(모델 가정) 초기화  
            W = torch.zeros(1, requires_grad = True) ♣  
            b = torch.zeros(1, requires_grad = True) ♣  
            - requires_grad=True : 학습할 것임을 명시  
            
            if. 함수 사용 안할 때  
            W = torch.zeros(1)  
            lr = 0.1  
        (2) Hypothesis(모델 가정) 계산  
            hypothesis = W * x_train + b  
            - W : weight  
            - Bias  
            
            if. 함수 사용 안할 때  
            hypothesis = W * x_train  
    3) Compute loss(손실 측정)  
<img src="./Compute_loss.png" width="400" height="400">  
        (2) Compute loss(손실 측정) 계산  
            Mean Squared Error(MSE) = cost(W, b) = torch.mean((hypothesis - y_train) ** 2)  
            
            if. 함수 사용 안할 때  
            따로 계산x
    4) Optimize(최적화)  
        (1) Optimize(최적화) 설정 : optimizer = torch.optim.옵티마이저 종류([학습시킬 변수], lr=학습률) ♣  
            - 확률적 경사하강법 : optimizer = torch.optim.SGD([W, b], lr=0.01) ♣  
<img src="./Gradient_Descent.png" width="400" height="400">  
<img src="./Gradient_Descent2.png" width="400" height="400">  
        (2) Optimize(최적화)를 통한 학습  
            - gradient 초기화 : optimizer.zero_grad() ♣  
            - gradient 계산 : cost.backward() ♣  
            - 모델 개선 : optimizer.step() ♣  
            
            if. 함수 사용 안할 때  
            gradient = torch.sum((W * x_train - y_train) * x_train)  
            W -= lr * gradient  
    - (2)는 for epoch in range(nb_epochs)로 돌림  
    5) 결과 출력  
        print('Epoch {:4d}/{}, W: {:.3f}, Cost : {:.6f}'.format(epoch, nb_epochs, W.item(), cost.item())) ♣  
    6) 딥러닝 목적  
        - 최적 W, b 탐색  
        - Cost 최소화  

In [2]:
import numpy as np
import torch

In [8]:
# Data definition(데이터 정의)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(x_train)
print(y_train)

tensor([[1.],
        [2.],
        [3.]])
tensor([[2.],
        [4.],
        [6.]])


In [6]:
# Hypothesis(모델 가정)
W = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 것임을 명시
b = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 것임을 명시
hypothesis = W * x_train + b
print(W)
print(b)
print(hypothesis)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)
tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [7]:
# Compute loss(손실 측정)
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

# Optimize(최적화)
optimizer = optim.SGD([W, b], lr=0.01)
optimizer.zero_grad()
cost.backward()
optimizer.step()

tensor(18.6667, grad_fn=<MeanBackward0>)


In [15]:
# 전체 코드

# Data definition(데이터 정의)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# Hypothesis(모델 가정) 초기화
W = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 것임을 명시
b = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 것임을 명시

# Optimize(최적화) 정의
optimizer = torch.optim.SGD([W, b], lr=0.01)

nb_epochs = 1000
for epoch in range(1, nb_epochs + 1):
    # Hypothesis(모델 가정) 예측
    hypothesis = W * x_train + b
    # Compute loss(손실 측정) 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # Optimize(최적화) 학습
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
print(W)
print(b)

tensor([1.9708], requires_grad=True)
tensor([0.0664], requires_grad=True)


In [16]:
# 옵티마이저 함수 사용x 전체 코드

# Data definition(데이터 정의)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# Hypothesis(모델 가정) 초기화
W = torch.zeros(1)
# learning rate 설정
lr = 0.1

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    # Hypothesis(모델 가정) 예측
    hypothesis = W * x_train
    # Compute loss(손실 측정) 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    gradient = torch.sum((W * x_train - y_train) * x_train)
    
    print('Epoch {:4d}/{}, W: {:.3f}, Cost : {:.6f}'.format(epoch, nb_epochs, W.item(), cost.item()))
    
    # Optimize(최적화) 학습
    W -= lr * gradient

Epoch    0/10 W: 0.000, Cost : 4.666667
Epoch    1/10 W: 1.400, Cost : 0.746666
Epoch    2/10 W: 0.840, Cost : 0.119467
Epoch    3/10 W: 1.064, Cost : 0.019115
Epoch    4/10 W: 0.974, Cost : 0.003058
Epoch    5/10 W: 1.010, Cost : 0.000489
Epoch    6/10 W: 0.996, Cost : 0.000078
Epoch    7/10 W: 1.002, Cost : 0.000013
Epoch    8/10 W: 0.999, Cost : 0.000002
Epoch    9/10 W: 1.000, Cost : 0.000000
Epoch   10/10 W: 1.000, Cost : 0.000000
