Pytorch 공부 사이트 : https://wikidocs.net/52460  

 1. 목차  
	1) 데이터 정의(Data definition)  
	2) 모델 가정(Hypothesis)  
	3) 손실 측정(Compute loss)  
    4) 최적화(Optimize)  
    5) 결과 출력  
	6) 경사 하강법(Gradient Descent)  
    7) 단일변수 선형회귀(SimpleLinear Regression)  
 2. 단일변수 선형회귀(SimpleLinear Regression) : 1개의 데이터 다룸  
    1) 데이터 정의(Data definition)  
<img src="./Data_definition.png" width="200" height="200">  
        (1) Traing dataset정의  
            - 입력 : x_train = torch.FloatTensor([인덱스 범위])  
            - 출력 : y_train = torch.FloatTensor([인덱스 범위])  
        (2) Test dataset정의  
            - 입력 : x_test =  
            - 출력 : y_test =  
    2) 모델 가정(Hypothesis)  
<img src="./Hypothesis.png" width="300" height="300">  
        (1) # 모델 가정(Hypothesis) 초기화  
            W = torch.zeros(1, requires_grad = True) ♣  
            b = torch.zeros(1, requires_grad = True) ♣  
            - 1 : 입력 차원  
            - requires_grad=True : 학습할 것임을 명시  
            
            if. 함수 사용 안할 때 ♣  
            W = torch.zeros(1)  
            lr = 0.1  
        (2) 모델 가정(Hypothesis) 예측  
            hypothesis = W * x_train + b  
            - W : weight  
            - b : Bias  
            
            if. 함수 사용 안할 때 ♣  
            hypothesis = W * x_train  
    3) 손실 측정(Compute loss)  
<img src="./Compute_loss.png" width="400" height="400">  
        (2) 손실 측정(Compute loss) 계산  
            Mean Squared Error(MSE) = cost(W, b) = torch.mean((hypothesis - y_train) ** 2)  
            
            if. 함수 사용 안할 때 ♣  
            따로 계산x
    4) 최적화(Optimize)  
        (1) 최적화(Optimize) 설정 : optimizer = torch.optim.옵티마이저 종류([학습시킬 변수], lr=학습률) ♣  
            - 확률적 경사하강법 : optimizer = torch.optim.SGD([W, b], lr=0.01) ♣  
<img src="./Gradient_Descent.png" width="400" height="400">  
<img src="./Gradient_Descent2.png" width="400" height="400">  
        (2) 최적화(Optimize)를 통한 학습  
            - gradient 초기화 : optimizer.zero_grad() ♣  
            - cost함수 미분 = cost가 감소하는 부분 = gradient 계산 : cost.backward() ♣  
            - W, b 업데이트 : optimizer.step() ♣  
            
            if. 함수 사용 안할 때 ♣  
            gradient = torch.sum((W * x_train - y_train) * x_train)  
            W -= lr * gradient  

    - (2)는 for epoch in range(nb_epochs)로 돌림  
    5) 결과 출력  
        print('Epoch {:4d}/{}, W : {:.3f}, Cost : {:.6f}'.format(epoch, nb_epochs, W.item(), cost.item())) ♣  
    6) 딥러닝 목적  
        - 최적 W, b 탐색  
        - Cost 최소화  

In [1]:
import numpy as np
import torch

In [2]:
# 1) 데이터 정의(Data definition)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(x_train)
print(y_train)

tensor([[1.],
        [2.],
        [3.]])
tensor([[2.],
        [4.],
        [6.]])


In [3]:
# 2) 모델 가정(Hypothesis)
W = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 것임을 명시
b = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 것임을 명시
hypothesis = W * x_train + b
print(W)
print(b)
print(hypothesis)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)
tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [5]:
# 3) 손실 측정(Compute loss)
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

# 4) 최적화(Optimize)
optimizer = torch.optim.SGD([W, b], lr=0.01)
optimizer.zero_grad()
cost.backward()
optimizer.step()

tensor(18.6667, grad_fn=<MeanBackward0>)


In [15]:
# 전체 코드

# 1) 데이터 정의(Data definition)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 2) 모델 가정(Hypothesis) 초기화
W = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 것임을 명시
b = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 것임을 명시

# 3) 최적화(Optimize) 정의
optimizer = torch.optim.SGD([W, b], lr=0.01)

nb_epochs = 1000
for epoch in range(1, nb_epochs + 1):
    # 4) 모델 가정(Hypothesis) 예측
    hypothesis = W * x_train + b
    # 5) 손실 측정(Compute loss) 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # 6) 최적화(Optimize) 학습
    optimizer.zero_grad()
    cost.backward() # cost함수 미분 ♣
    optimizer.step() # W, b 업데이트 ♣
print(W)
print(b)

tensor([1.9708], requires_grad=True)
tensor([0.0664], requires_grad=True)


In [16]:
# 옵티마이저 함수 사용x 전체 코드

# 1) 데이터 정의(Data definition)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# 2) 모델 가정(Hypothesis) 초기화
W = torch.zeros(1)
# 2) 최적화(Optimize) 정의
lr = 0.1

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    # 4) 모델 가정(Hypothesis) 예측
    hypothesis = W * x_train
    # 5) 손실 측정(Compute loss) 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    print('Epoch {:4d}/{}, W: {:.3f}, Cost : {:.6f}'.format(epoch, nb_epochs, W.item(), cost.item()))
    
    # 6) 최적화(Optimize) 학습
    gradient = torch.sum((W * x_train - y_train) * x_train) # cost함수 미분 ♣
    W -= lr * gradient # W, b 업데이트 ♣

Epoch    0/10 W: 0.000, Cost : 4.666667
Epoch    1/10 W: 1.400, Cost : 0.746666
Epoch    2/10 W: 0.840, Cost : 0.119467
Epoch    3/10 W: 1.064, Cost : 0.019115
Epoch    4/10 W: 0.974, Cost : 0.003058
Epoch    5/10 W: 1.010, Cost : 0.000489
Epoch    6/10 W: 0.996, Cost : 0.000078
Epoch    7/10 W: 1.002, Cost : 0.000013
Epoch    8/10 W: 0.999, Cost : 0.000002
Epoch    9/10 W: 1.000, Cost : 0.000000
Epoch   10/10 W: 1.000, Cost : 0.000000
