In [3]:
# !pip install torch

In [2]:
import numpy as np
import torch

In [3]:
# 1차원 배열 numpy
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
# 배열 차원, 원소 개수
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

[0. 1. 2. 3. 4. 5. 6.]
Rank of t :  1
Shape of t :  (7,)


In [4]:
# 1차원 배열 슬라이싱
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [22]:
# 2차원 배열 numpy
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
# 배열 차원 ,원소 개수
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t :  2
Shape of t :  (4, 3)


In [28]:
# 2차원 배열 슬라이싱
print(t[:, 1])
print(t[:, :-1])

[ 2.  5.  8. 11.]
[[ 1.  2.]
 [ 4.  5.]
 [ 7.  8.]
 [10. 11.]]


In [7]:
# 1차원 배열 torch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
# 배열 차원 ,원소 개수
print(t.dim())
print(t.shape)
print(t.size())

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [8]:
# 1차원 배열 슬라이싱
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [9]:
# 2차원 배열 torch
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
# 배열 차원, 원소 개수
print(t.dim())
print(t.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])


In [10]:
# 2차원 배열 슬라이싱
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [11]:
# 행렬 덧셈 - 같은 차원, 같은 원소 갯수 배열 연산
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [12]:
# 행렬 덧셈 - 다른 차원, 다른 원소 갯수 배열 연산
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]]) # 차원을 2x1로 늘려줌 >> 3, 3
print(m1 + m2)

m1 = torch.FloatTensor([[1, 2]]) # 차원을 2x2로 늘려줌 >> 1, 2, 1, 2
m2 = torch.FloatTensor([[3], [4]]) # 차원을 2x2로 늘려줌 >> 3, 4, 3, 4
print(m1 + m2)

tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [17]:
# 행렬 곱
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ', m1.shape) # 2x2
print('Shape of Matrix 2 : ', m2.shape) # 2x1
print(m1.matmul(m2)) # 2x1
# 행렬 원소 곱
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ', m1.shape) # 2x2
print('Shape of Matrix 2 : ', m2.shape) # 2x1
print(m1 * m2)
print(m1.mul(m2))

Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [19]:
# 행렬 원소 평균 - 1차원
t = torch.FloatTensor([1, 2])
print(t.mean())
# 행렬 원소 평균 - 2차원
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0)) # 행렬에서 첫번째 차원(행) 제거. 열의 차원은 유지
print(t.mean(dim=1)) # 행렬에서 두번째 차원(열) 제거. 행의 차원은 유지
print(t.mean(dim=-1)) # 행렬에서 마지막 차원(열) 제거. 행의 차원은 유지
# 행렬 원소 평균 오류
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

tensor(1.5000)
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [20]:
# 행렬 원소 덧셈 - 1차원
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum())
# 행렬 원소 덧셈 - 2차원
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [21]:
# 행렬 원소 최대값 - 1차원
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())
# 행렬 원소 최대값 - 2차원
print(t.max(dim=0))
print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
