# 3. Tensors
    1) 특징
        - 다차원 배열 다룸
        - numpy의 ndarrays와 유사
        
    2) Tensor Quickstart
        1] initilaize
            [1] python list -> numpy
            [2] numpy -> tensor
            [3] another tensor -> tensor
                1]] retains the properties of x
                2]] overrides the datatype of x
            [4] random or constant value tensor
        2] Operation
            [1] Move device
                - device간 data 이동(Runtime -> Change runtime type -> GPU)
                - device 위치 : data와 model이 같은 device에 위치해야 학습 가능
                - 단점 : load 소모 큼
                - 장점 : GPU를 활용한 tensor 연산 시, 연산속도 크게 증가
                       (load 소모가 매우 크다는 단점을 극복할 정도의 속도 출력 가능)
            [2] Indexing and Slicing
            [3] Joining
                - .cat : 기존 차원에 tensor를 연속적으로 붙임
                - .stack : 새로운 차원에 tensor를 연속적으로 붙임
            [4] Arithmetic operaitons
            [5] Manipulate tensor shape
                - .transpose : 두 차원의 순서 swap
                - .permute : 차원의 순서 change
                - .reshape : 원소의 순서와 개수를 보존하면서 tensor의 모양 change
        3] Bridge with Numpy
            [1] tensor -> numpy
            [2] numpy -> tensor

In [1]:
import torch
import numpy as np

print(torch.cuda.is_available())
print(torch.cuda.current_device())
print(torch.cuda.get_device_name())

True
0
NVIDIA GeForce RTX 3060


In [2]:
# 1] initilaize
#     [1] python list -> numpy
#     [2] numpy -> tensor
#     [3] another tensor -> tensor
#         1]] retains the properties of x
#         2]] overrides the datatype of x
#     [4] random or constant value tensor

# [1] python list -> numpy
py_list = [[1, 2], [3, 4]]
x = torch.tensor(py_list)

# [2] numpy -> tensor
np_array = np.array(py_list)
x = torch.from_numpy(np_array)

# [3] another tensor -> tensor
# 1]] retains the properties of x
x_ones = torch.ones_like(x)
print(f'Ones Tensor: \n {x_ones} \n')

# 2]] overrides the datatype of x
x_rand = torch.rand_like(x, dtype=torch.float)
print(f'Random Tensor: \n {x_rand} \n')

# [4] random or constant value tensor
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]], dtype=torch.int32) 

Random Tensor: 
 tensor([[0.6866, 0.3475],
        [0.3383, 0.1443]]) 

Random Tensor: 
 tensor([[0.1853, 0.7534, 0.2875],
        [0.6143, 0.1232, 0.8950]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [3]:
# 2] Operation
#     [1] Move device
#         - device간 data 이동(Runtime -> Change runtime type -> GPU)
#         - device 위치 : data와 model이 같은 device에 위치해야 학습 가능
#         - 단점 : load 소모 큼
#         - 장점 : GPU를 활용한 tensor 연산 시, 연산속도 크게 증가
#                (load 소모가 매우 크다는 단점을 극복할 정도의 속도 출력 가능)
#     [2] Indexing and Slicing
#     [3] Joining
#         - .cat : 기존 차원에 tensor를 연속적으로 붙임
#         - .stack : 새로운 차원에 tensor를 연속적으로 붙임
#     [4] Arithmetic operaitons
#     [5] Manipulate tensor shape
#         - .transpose : 두 차원의 순서 swap
#         - .permute : 차원의 순서 change
#         - .reshape : 원소의 순서와 개수 보존하면서 tensor의 모양 change

# [1] Mode device
tensor = torch.rand((3, 4))
print(tensor.device)

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(tensor.device)

tensor = tensor.to('cpu')
print(tensor.device)

# [2] Indexing and Slicing
tensor = torch.ones((4, 4))
print(tensor)
print(f'First row: {tensor[0]}') # 첫번재 행
print(f'First column: {tensor[:, 0]}') # 첫번재 열
print(f'Last column: {tensor[..., -1]}') # 마지막 열

tensor[:, 1] = 0
print(tensor)

# [3] Joining
#     - .cat : 지정한 기존 차원에 tensor를 연속적으로 붙임
#     - .stack : 지정한 새로운 차원에 tensor를 연속적으로 붙임

tensor = torch.ones((4, 4))
# .cat
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1.shape)

# .stack
t2 = torch.stack([tensor, tensor, tensor], dim = 1)
print(t2.shape)

# [4] Arithmetic operaitons
x1 = torch.rand((2, 3))
x2 = torch.rand((2, 3))
x3 = torch.rand((3, 2))

y1 = x1 + x2
y2 = x1 * x2 # elementwise multiplication
y3 = x1 @ x3 # matrix multiplication(A @ B = [N x M] @ [M x K])

print(y1.shape)
print(y2.shape)
print(y3.shape)

# [5] Manipulate tensor shape
#     - .transpose : 두 차원의 순서 swap
#     - .permute : 차원의 순서 change
#     - .reshape : 원소의 순서를 보존하면서 tensor의 모양 change

x = torch.rand((4, 3, 2, 5))

# .transpose
y1 = x.transpose(1, 3)
print(y1.shape)

# .permute
y2 = x.permute(1, 0, 3, 2) # 기존에 n번째 차원인 부분을 현재 설정한 위치에 둔다
print(y2.shape)

# .reshape
x = torch.rand((2, 3))

y1 = x.reshape((3, 2)) # 기존 원소 개수 = reshape 원소 개수
y2 = x.reshape((-1, )) # 1개 행에 전부 표시

print(x)
print(y1)
print(y2)

cpu
cuda:0
cpu
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([4, 12])
torch.Size([4, 3, 4])
torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([2, 2])
torch.Size([4, 5, 2, 3])
torch.Size([3, 4, 5, 2])
tensor([[0.6983, 0.5678, 0.8518],
        [0.6581, 0.0045, 0.8700]])
tensor([[0.6983, 0.5678],
        [0.8518, 0.6581],
        [0.0045, 0.8700]])
tensor([0.6983, 0.5678, 0.8518, 0.6581, 0.0045, 0.8700])


In [4]:
# 3] Bridge with Numpy
#     [1] tensor -> numpy
#     [2] numpy -> tensor

n = np.ones(5)
t = torch.from_numpy(n)
n2 = t.numpy()

print(type(n))
print(type(t))
print(type(n2))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


# 4. Datasets & DataLoaders(torch.utils.data)
    1) Datasets
        (1) Bulit In Dataset
            1] Load built in dataset
                - Pytorch에서 제공하는 유명한 dataset
                ex. torchvision.datasets.FashionMNIST
                    - root : train/test data 경로
                    - train : train/test dataset 지정
                    - transform : input에 대한 전처리 과정 지정
                    - target_transform : label에 대한 전처리 과정 지정
                    - download : data 다운로드
                ex. torchvision.datasets.ImageNet
                    - root : train/test data 경로
                    - split : train/validation dataset 지정
                    - transform : input에 대한 전처리 과정 지정
                    - target_transform : label에 대한 전처리 과정 지정

                    - dataset의 용량이 매우 커서 download 옵션 지원x
                ex. 데이터셋 : CIFAR-10
                    (1) 데이터셋 특징
                        1] 데이터 개수
                            - Train : 50,000
                            - Test : 10,000
                        2] 컬러 : 컬러
                        3] 라벨(클래스) 개수 : 10(0 ~ 9)
                        4] 이미지 크기 : 32 x 32
                        5] 픽셀값 : 0 ~ 255
        (2) Custom Dataset
            1] Prepare data
                - 보편적인 데이터 경로 : root -> train/val -> classes -> images
            2] Import packages
            3] Custom Dataset
                - 보편적인 Dataset : Dataset class 상속
                - __init__ : __getitem__ 메소드에서 필요한 변수 정의(객체 생성시 한번만 실행)
                - __len__ : 샘플의 개수 반환
                - __getitem__ : 인덱스 받아서 single input-label 쌍 반환
            4] Test a custom dataset(test code)
            
            이전 예제 : Cifar10에 모든 데이터 존재
            현재 예제 : train, test 폴더에 데이터가 나뉘어져 존재
                - Cifar10/train
                - Cifar10/test
                -> train 파라미터 사용x

                -> target_transform은 잘 사용하지 않으므로 파라미터 사용x
    2) DataLoader
        (1) 기능
            - dataset의 input-label을 한 개의 샘플로 생성
            - mini batch / reshuffle 수행
        (2) 파라미터
            - dataset : dataset 지정
            - batch_size=1 : batch 당 load할 샘플 개수
            - shuffle=None : 샘플 랜덤 추출 설정
                train -> shuffle 필요o
                test -> shuffle 필요x
            - num_workers=0 : data load에 사용할 subprocess 개수 설정(0 : main process에만 load)
                batch_size 증가, 전처리 과정 많음 -> worker 수 증가(worker 처리 성능 > worker 생성 종료 및 통신 소요시간)
                batch_size 감소, 전처리 과정 적음 -> worker 수 감소(worker 처리 성능 < worker 생성 종료 및 통신 소요시간)
                -> worker를 늘리는 것은 상황에 따라 좋을 수도, 안좋을 수도 있다
            - drop_last=False : 남은 batch data의 drop 여부 결정
                train -> drop_last 무방(shuffle 하기 때문)
                test -> drop_last 안됨(모든 데이터 사용으로 정확한 측정을 위해)
            
                    - root : train/test data 경로
                    - train : train/test dataset 지정
                    - transform : input에 대한 전처리 과정 지정
                    - target_transform : label에 대한 전처리 과정 지정
                    - download : data 다운로드

In [7]:
# (1) Bulit In Dataset
#     1] Load built in dataset
#         - Pytorch에서 제공하는 유명한 dataset
#         ex. torchvision.datasets.FashionMNIST
#             - root : train/test data 경로
#             - train : train/test dataset 지정
#             - transform : input에 대한 전처리 과정 지정
#             - target_transform : label에 대한 전처리 과정 지정
#             - download : data 다운로드
#         ex. torchvision.datasets.ImageNet
#             - root : train/test data 경로
#             - split : train/validation dataset 지정
#             - transform : input에 대한 전처리 과정 지정
#             - target_transform : label에 대한 전처리 과정 지정
#             - dataset의 용량이 매우 커서 download 옵션 지원x

import torch
import torchvision
import torchvision.transforms as T

train_set = torchvision.datasets.FashionMNIST(
    root = 'data', 
    train = True, 
    download = True, 
    transform = T.ToTensor()
)
train_set = torchvision.datasets.FashionMNIST(
    root = 'data', 
    train = False, 
    download = True, 
    transform = T.ToTensor()
)

In [8]:
# (2) Custom Dataset
#     1] Prepare data
#         - 보편적인 데이터 경로 : root -> train/val -> classes -> images
#     2] Import packages
#     3] Custom Dataset
#         - 보편적인 Dataset : Dataset class 상속
#         - __init__ : __getitem__ 메소드에서 필요한 변수 정의(객체 생성시 한번만 실행)
#         - __len__ : 샘플의 개수 반환
#         - __getitem__ : 인덱스 받아서 single input-label 쌍 반환
#     4] Test a custom dataset(test code)

#     이전 예제 : Cifar10에 모든 데이터 존재
#     현재 예제 : train, test 폴더에 데이터가 나뉘어져 존재
#         - Cifar10/train
#         - Cifar10/test
#         -> train 파라미터 사용x

#         -> target_transform은 잘 사용하지 않으므로 파라미터 사용x

In [9]:
# 1] Prepare data
#     - 보편적인 데이터 경로 : root -> train/val -> classes -> images

In [10]:
# 2] Import packages

import os
import glob
import torch
import torchvision.transforms as T

from torch.utils.data import Dataset, DataLoader
from PIL import Image

In [11]:
# 3] Custom Dataset
#     - 보편적인 Dataset : Dataset class 상속
#     - __init__ : __getitem__ 메소드에서 필요한 변수 정의(객체 생성시 한번만 실행)
#     - __len__ : 샘플의 개수 반환
#     - __getitem__ : 인덱스 받아서 single input-label 쌍 반환

# 이전 예제 : Cifar10에 모든 데이터 존재
# 현재 예제 : train, test 폴더에 데이터가 나뉘어져 존재
#     - Cifar10/train
#     - Cifar10/test
#     -> train 파라미터 사용x

#     -> target_transform은 잘 사용하지 않으므로 파라미터 사용x

class Cifar10(Dataset):
    def __init__(self, root, transform = None):
        super(Cifar10, self).__init__()
        self.make_dataset(root) # 데이터셋 생성
        self.transform = transform # transform 설정
        
    def make_dataset(self, root):
        self.data = []
        categories = os.listdir(root) # root 내부 폴더 or 파일 불러오기(여기서는 class명이 폴더명이다!)
        categories = sorted(categories)
        for label, category in enumerate(categories):
            images = glob.glob(f'{root}/{category}/*.png') # 이미지 경로 불러오기
            for image in images:
                self.data.append((image, label)) # self.data[0] = [image, label]
                
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        image, label = self.data[idx]
        image = self.read_image(image) # 이미지 원본 불러오기
        if self.transform is not None:
            image = self.transform(image)
        return image, label
    
    def read_image(self, path):
        image = Image.open(path) # 실제 이미지
        return image.convert('RGB') # 흑백 : 1x32x32 / 컬러 : 3x32x32 -> 서로 차원이 조금 다르므로 3x32x32로 통일

In [13]:
# 4] Test a custom dataset(test code)

transform = T.Compose([
    T.ToTensor(), 
    T.Normalize((0.5, 0.5, 0.5), (0.25, 0.25, 0.25)) # fashionMNIST : ((0.5, 0.5)) -> 1xHxW / Cifar10 : ((0.5, 0.5, 0.5), (0.25, 0.25, 0.25)) -> 3xHxW
])
train_root = 'data/Cifar10/train'

train_data = Cifar10(train_root, transform)

for image, label in train_data:
    print(image.shape, label)
    break

torch.Size([3, 32, 32]) 0


In [14]:
# 2) DataLoader
#     (1) 기능
#         - dataset의 input-label을 한 개의 샘플로 생성
#         - mini batch / reshuffle 수행
#     (2) 파라미터
#         - dataset : dataset 지정
#         - batch_size=1 : batch 당 load할 샘플 개수
#         - shuffle=None : 샘플 랜덤 추출 설정
#             train -> shuffle 필요o
#             test -> shuffle 필요x
#         - num_workers=0 : data load에 사용할 subprocess 개수 설정(0 : main process에만 load)
#             batch_size 증가, 전처리 과정 많음 -> worker 수 증가(worker 처리 성능 > worker 생성 종료 및 통신 소요시간)
#             batch_size 감소, 전처리 과정 적음 -> worker 수 감소(worker 처리 성능 < worker 생성 종료 및 통신 소요시간)
#             -> worker를 늘리는 것은 상황에 따라 좋을 수도, 안좋을 수도 있다
#         - drop_last=False : 남은 batch data의 drop 여부 결정
#             train -> drop_last 무방(shuffle 하기 때문)
#             test -> drop_last 안됨(모든 데이터 사용으로 정확한 측정을 위해)

#                             - root : train/test data 경로
#                 - train : train/test dataset 지정
#                 - transform : input에 대한 전처리 과정 지정
#                 - target_transform : label에 대한 전처리 과정 지정
#                 - download : data 다운로드

transform = T.Compose([
    T.ToTensor(), 
    T.Normalize((0.5, 0.5, 0.5), (0.25, 0.25, 0.25))
])
train_root = 'data/Cifar10/train'
train_data = Cifar10(train_root, transform)
train_loader = DataLoader(train_data, batch_size=64, shuffle=True, drop_last=True)

test_root = 'data/Cifar10/test'
test_data = Cifar10(test_root, transform)
test_loader = DataLoader(test_data, batch_size=1)

print(len(train_data), len(train_loader))
print(len(test_data), len(test_loader))

50000 781
10000 10000
