In [1]:
import torch
import numpy as np

In [2]:
py_list = [[1, 2], [3, 4]]
x = torch.tensor(py_list)

In [3]:
np_array = np.array(py_list)
x = torch.from_numpy(np_array)

In [4]:
# retains the properties of x
x_ones = torch.ones_like(x) 
print(f'Ones Tensor: \n {x_ones} \n')

# overrides the datatype of x
x_rand = torch.rand_like(x, dtype=torch.float) 
print(f'Random Tensor: \n {x_rand} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1349, 0.6128],
        [0.7072, 0.7982]]) 



In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor}')

Random Tensor: 
 tensor([[0.4134, 0.1814, 0.0182],
        [0.8580, 0.2316, 0.2224]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand((3,4))

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
# We move our tensor to the GPU if available
tensor = torch.rand((3,4))
print(tensor.device)

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(tensor.device)

tensor = tensor.to('cpu')
print(tensor.device)

cpu
cuda:0
cpu


In [8]:
tensor = torch.ones((4, 4))
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')
print(f'Last column: {tensor[..., -1]}')
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
tensor = torch.ones((4, 4))
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1.shape)

t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2.shape)

torch.Size([4, 12])
torch.Size([4, 3, 4])


In [10]:
x1 = torch.rand((2, 3))
x2 = torch.rand((2, 3))
x3 = torch.rand((3, 2))

y1 = x1 + x2
y2 = x1 * x2 # elementwise multiplication
y3 = x1 @ x3 # matrix multiplication

print(y1.shape)
print(y2.shape)
print(y3.shape)

torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([2, 2])


In [12]:
x = torch.rand((4, 3, 2, 5))

y1 = x.transpose(1, 3)
y2 = x.permute(1, 0, 3, 2)

print(y1.shape)
print(y2.shape)

torch.Size([4, 5, 2, 3])
torch.Size([3, 4, 5, 2])


In [14]:
x = torch.rand((2, 3))

y1 = x.reshape((3, 2))
y2 = x.reshape((-1,))

print(x)
print(y1)
print(y2)

tensor([[0.4794, 0.9965, 0.0454],
        [0.5924, 0.2046, 0.7334]])
tensor([[0.4794, 0.9965],
        [0.0454, 0.5924],
        [0.2046, 0.7334]])
tensor([0.4794, 0.9965, 0.0454, 0.5924, 0.2046, 0.7334])


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)
n2 = t.numpy()

print(type(n))
print(type(t))
print(type(n2))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
